alias ga="git add ."
alias com="git commit -m"
alias push="git push"
alias pull="git pull"
alias t="touch"
alias x="chmod +x"
alias xc="chmod +x *.c"
alias xpy="chmod +x *.py"
alias xjs="chmod +x *.js"
alias b="betty"
alias sc="shellcheck"
alias semi="semistandard --fix"
alias d2u="dos2unix"
alias w3c="~/W3C-Validator/./w3c_validator.py"
alias compile="gcc -Wall -pedantic -Werror -Wextra -std=gnu89"
alias montycomp="gcc -Wall -Werror -Wextra -pedantic *.c -o monty"
alias sscompile="gcc -Wall -Werror -Wextra -pedantic -std=gnu89 *.c -o hsh"
alias teeset="tee *-*"
alias teec="tee *.c"
alias teepy="tee *.py"
alias teejs="tee *.js"

alias llp="cd ~/atlas-low_level_programming"
alias setup="cd ~/atlas-low_level_programming/setup"
alias rec="cd ~/atlas-low_level_programming/recursion"
alias sta="cd ~/atlas-low_level_programming/static_libraries"
alias arg="cd ~/atlas-low_level_programming/argc_argv"
alias mal="cd ~/atlas-low_level_programming/malloc_free"
alias mml="cd ~/atlas-low_level_programming/more_malloc_free"
alias pre="cd ~/atlas-low_level_programming/preprocessor"
alias tpd="cd ~/atlas-low_level_programming/structures_typedef"
alias fnp="cd ~/atlas-low_level_programming/function_pointers"
alias vdc="cd ~/atlas-low_level_programming/variadic_functions"
alias sll="cd ~/atlas-low_level_programming/singly_linked_lists"
alias msl="cd ~/atlas-low_level_programming/more_singly_linked_lists"
alias bit="cd ~/atlas-low_level_programming/bit_manipulation"
alias fio="cd ~/atlas-low_level_programming/file_io"
alias dll="cd ~/atlas-low_level_programming/doubly_linked_lists"
alias hsh="cd ~/atlas-low_level_programming/hash_tables"
alias src="cd ~/atlas-low_level_programming/search_algorithms"

alias hlp="cd ~/atlas-higher_level_programming"

alias prf="cd ~/atlas-printf"

alias shell="cd ~/atlas-simple_shell"

alias mty="cd ~/atlas-monty"

alias srt="cd ~/atlas-sorting_algorithms"

alias tre="cd ~/atlas-binary_trees"

alias zro="cd ~/atlas-zero_day"
