#!/usr/bin/env bash

echo -e alias ga=\"git add .\" > ~/.bash_aliases
echo -e alias com=\"git commit -m\" >> ~/.bash_aliases
echo -e alias push=\"git push\" >> ~/.bash_aliases
echo -e alias t=\"touch\" >> ~/.bash_aliases
echo -e alias x=\"chmod +x\" >> ~/.bash_aliases
echo -e alias b=\"betty\" >> ~/.bash_aliases
echo -e alias sc=\"shellcheck\" >> ~/.bash_aliases
echo -e alias llp=\"cd ~/atlas-low_level_programming/\" >> ~/.bash_aliases
echo -e alias set=\"cd ~/atlas-low_level_programming/setup\" >> ~/.bash_aliases
echo -e alias rec=\"cd ~/atlas-low_level_programming/recursion/\" >> ~/.bash_aliases
echo -e alias arg=\"cd ~/atlas-low_level_programming/argc_argv/\" >> ~/.bash_aliases
echo -e alias mal=\"cd ~/atlas-low_level_programming/malloc_free/\" >> ~/.bash_aliases
echo -e alias mml=\"cd ~/atlas-low_level_programming/more_malloc_free/\" >> ~/.bash_aliases
echo -e alias pre=\"cd ~/atlas-low_level_programming/preprocessor/\" >> ~/.bash_aliases
echo -e alias tpd=\"cd ~/atlas-low_level_programming/structures_typedef/\" >> ~/.bash_aliases

echo "'~/.bash_aliases' appended"
echo -e "\n"
