#!/usr/bin/env bash

echo -e alias ga=\"git add .\" > ~/.bash_aliases
echo -e alias com=\"git commit -m\" >> ~/.bash_aliases
echo -e alias push=\"git push\" >> ~/.bash_aliases
echo -e alias t=\"touch\" >> ~/.bash_aliases
echo -e alias x=\"chmod +x\" >> ~/.bash_aliases
echo -e alias b=\"betty\" >> ~/.bash_aliases
echo -e alias sc=\"shellcheck\" >> ~/.bash_aliases
echo -e alias llp=\"cd ~/atlas-low_level_programming/\" >> ~/.bash_aliases
echo -e alias rec=\"cd ~/atlas-low_level_programming/recursion/\" >> ~/.bash_aliases

echo "'~/.bash_aliases' appended"
echo -e "\n"
