#!/usr/bin/env bash

cd ~

if  test -d Betty; then
	cd Betty;
	./install.sh;
	echo -e "\nReady to check Betty compliance!"
else
	git clone https://github.com/hs-hq/Betty.git;
	cd Betty;
	./install.sh;
	echo -e "\nReady to check Betty compliance!"
fi
echo -e "\n"
